#                                 __                 __
#    __  ______  ____ ___  ____ _/ /____  ____  ____/ /
#   / / / / __ \/ __ `__ \/ __ `/ __/ _ \/ __ \/ __  /
#  / /_/ / /_/ / / / / / / /_/ / /_/  __/ /_/ / /_/ /
#  \__, /\____/_/ /_/ /_/\__,_/\__/\___/\____/\__,_/
# /____                     matthewdavis.io, holla!
#
include .make/Makefile.inc

NS                  ?= default
APP                 ?= mysql
MYSQL_DATABASE      ?= wordpress
MYSQL_USER          ?= wordpress
MYSQL_PASSWORD      ?= wordpress
MYSQL_ROOT_PASSWORD ?= wordpress
export

## Test installation
test:

	@echo "$(GREEN)"

	nslookup mysql

	@echo "$(RESET)"